[phases.setup]
nixPkgs = ["python311", "zlib", "cacert"]

[phases.install]
cmds = [
  "apt-get update -qq && apt-get install -y -qq default-libmysqlclient-dev pkg-config build-essential",
  "pip install -r requirements.txt"
]
