web: python manage.py migrate --noinput && python manage.py collectstatic --noinput --clear && gunicorn config.wsgi --bind 0.0.0.0:$PORT --workers 4 --log-level info --timeout 120
release: python manage.py migrate --noinput
