# Generated by Django 5.2.13 on 2026-05-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(db_index=True, max_length=254)),
                ('tipo', models.CharField(choices=[('BIENVENIDA', 'Bienvenida')], db_index=True, max_length=50)),
                ('asunto', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ERROR', 'Error')], db_index=True, max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('enviado_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('objeto_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'log de email',
                'verbose_name_plural': 'logs de emails',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['objeto_tipo', 'objeto_id'], name='notificatio_objeto__50062b_idx'), models.Index(fields=['tipo', 'estado'], name='notificatio_tipo_8b2a9b_idx')],
            },
        ),
    ]
