# Generated by Django 5.2 on 2026-06-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(db_index=True, max_length=254)),
                ('tipo', models.CharField(choices=[('bienvenida', 'Bienvenida'), ('asignacion_revisor', 'Asignacion de revisor'), ('veredicto', 'Veredicto emitido'), ('feedback', 'Feedback anonimo'), ('cambio_fecha', 'Cambio de fecha'), ('paper_reenviado', 'Paper reenviado a revision'), ('invitacion_revisor', 'Invitacion a revisor'), ('verificacion', 'Verificacion de correo')], db_index=True, max_length=30)),
                ('asunto', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('error', 'Error')], db_index=True, default='enviado', max_length=10)),
                ('error_msg', models.TextField(blank=True)),
                ('enviado_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('objeto_tipo', models.CharField(blank=True, max_length=50)),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de email',
                'verbose_name_plural': 'Logs de emails',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['objeto_tipo', 'objeto_id'], name='notificatio_objeto__50062b_idx'), models.Index(fields=['tipo', 'estado'], name='notificatio_tipo_8b2a9b_idx')],
            },
        ),
    ]
