# Generated by Django 5.2.13 on 2026-05-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Log de email', 'verbose_name_plural': 'Logs de emails'},
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('error', 'Error')], db_index=True, default='enviado', max_length=10),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='objeto_tipo',
            field=models.CharField(blank=True, default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='tipo',
            field=models.CharField(choices=[('bienvenida', 'Bienvenida'), ('asignacion_revisor', 'Asignacion de revisor'), ('veredicto', 'Veredicto emitido'), ('feedback', 'Feedback anonimo'), ('cambio_fecha', 'Cambio de fecha'), ('paper_reenviado', 'Paper reenviado a revision')], db_index=True, max_length=30),
        ),
    ]
