# Generated by Django 5.2 on 2026-05-10 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('es_publico', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('visibilidad', models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada')], default='publica', max_length=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('abierta', 'Abierta'), ('en_revision', 'En revisión'), ('cerrada', 'Cerrada'), ('archivada', 'Archivada')], default='borrador', max_length=15)),
                ('slug', models.SlugField(help_text='Identificador único en la URL. Se genera automáticamente.', max_length=255, unique=True)),
                ('imagen_banner', models.ImageField(blank=True, null=True, upload_to='conferencias/banners/')),
                ('sitio_web', models.URLField(blank=True)),
                ('lugar', models.CharField(blank=True, max_length=255)),
                ('areas_tematicas', models.JSONField(default=list, help_text='Lista de áreas temáticas disponibles para las postulaciones.')),
                ('fecha_apertura_postulaciones', models.DateField(blank=True, help_text='Desde cuándo se pueden enviar postulaciones.', null=True)),
                ('fecha_cierre_postulaciones', models.DateField(blank=True, help_text='Hasta cuándo se aceptan postulaciones.', null=True)),
                ('fecha_limite_cambios', models.DateField(blank=True, help_text='RF-16: Plazo para que el autor reenvíe el paper con cambios.', null=True)),
                ('es_de_pago', models.BooleanField(default=False)),
                ('monto_inscripcion', models.DecimalField(blank=True, decimal_places=2, help_text='Monto en USD que el ponente debe pagar para postular.', max_digits=8, null=True)),
                ('formulario_postulacion', models.JSONField(default=list, help_text='Campos personalizados del formulario. Cada elemento: {"nombre": str, "tipo": str, "requerido": bool, "opciones": list}')),
                ('formatos_archivo_permitidos', models.JSONField(default=list, help_text='Ej: ["pdf", "docx"]. Vacío = sin restricción.')),
                ('max_autores', models.PositiveSmallIntegerField(default=5, help_text='Número máximo de autores por ponencia.')),
                ('min_revisores', models.PositiveSmallIntegerField(default=2, help_text='Mínimo de revisores por ponencia.')),
                ('max_revisores', models.PositiveSmallIntegerField(default=3, help_text='Máximo de revisores por ponencia. El 3ro se asigna en caso de empate.')),
                ('asignacion_automatica', models.BooleanField(default=False, help_text='RF-13: Si True, el sistema asigna revisores por área temática.')),
                ('rubrica', models.JSONField(default=list, help_text='Criterios de evaluación. Cada elemento: {"criterio": str, "descripcion": str, "peso": float}')),
                ('es_plantilla', models.BooleanField(default=False, help_text='Si True, esta conferencia puede usarse como plantilla.')),
                ('organizador', models.ForeignKey(limit_choices_to={'rol__in': ['organizador', 'administrador']}, on_delete=django.db.models.deletion.PROTECT, related_name='conferencias_organizadas', to=settings.AUTH_USER_MODEL)),
                ('plantilla_origen', models.ForeignKey(blank=True, help_text='Plantilla a partir de la cual se creó esta conferencia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferencias_derivadas', to='conferences.conferencia')),
            ],
            options={
                'verbose_name': 'Conferencia',
                'verbose_name_plural': 'Conferencias',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='InvitacionRevisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Correo al que se envía la invitación.', max_length=254)),
                ('token', models.CharField(help_text='Token único para aceptar la invitación desde el email.', max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='pendiente', max_length=10)),
                ('enviada_en', models.DateTimeField(auto_now_add=True)),
                ('respondida_en', models.DateTimeField(blank=True, null=True)),
                ('expira_en', models.DateField(help_text='Fecha límite para aceptar la invitación.')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='conferences.conferencia')),
                ('usuario', models.ForeignKey(blank=True, help_text='Se vincula si el email ya corresponde a un usuario registrado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitación a revisor',
                'verbose_name_plural': 'Invitaciones a revisores',
                'ordering': ['-enviada_en'],
            },
        ),
        migrations.CreateModel(
            name='ConferenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('organizador', 'Organizador'), ('revisor', 'Revisor'), ('autor', 'Autor'), ('supervisor', 'Supervisor')], max_length=15)),
                ('categoria_revisor', models.CharField(blank=True, max_length=100)),
                ('invitado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='conferences.conferencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante de conferencia',
                'verbose_name_plural': 'Participantes de conferencia',
                'unique_together': {('conferencia', 'usuario', 'rol')},
            },
        ),
    ]
