# Generated by Django 5.2 on 2026-06-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenciausuario',
            name='rol',
            field=models.CharField(choices=[('organizador', 'Organizador'), ('revisor', 'Revisor'), ('autor', 'Autor'), ('asistente', 'Asistente'), ('supervisor', 'Supervisor')], max_length=15),
        ),
    ]
