# Generated by Django 5.2 on 2026-06-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verificacionemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacionemail',
            name='codigo',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
