# Generated by Django 5.2 on 2026-05-08 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('resumen', models.TextField()),
                ('area_tematica', models.CharField(help_text='Debe coincidir con alguna de las áreas temáticas de la conferencia.', max_length=100)),
                ('autores', models.JSONField(default=list, help_text='Coautores adicionales al autor principal.')),
                ('archivo', models.FileField(help_text='Archivo del trabajo original.', upload_to='ponencias/archivos/')),
                ('archivo_revisado', models.FileField(blank=True, help_text='RF-16: Archivo reenviado por el autor tras pedir cambios.', null=True, upload_to='ponencias/revisados/')),
                ('estado', models.CharField(choices=[('postulada', 'Postulada'), ('en_revision', 'En revisión'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('aceptada_con_cambios', 'Aceptada con cambios'), ('cambios_enviados', 'Cambios enviados')], default='postulada', max_length=25)),
                ('comentario_estado', models.TextField(blank=True, help_text='Motivo o feedback al cambiar de estado (visible para el autor).')),
                ('pago_confirmado', models.BooleanField(default=False)),
                ('pago_referencia', models.CharField(blank=True, help_text='Referencia o ID de transacción del pago.', max_length=100)),
                ('postulada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cambios_enviados_en', models.DateTimeField(blank=True, null=True)),
                ('autor_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ponencias', to=settings.AUTH_USER_MODEL)),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponencias', to='conferences.conferencia')),
            ],
            options={
                'verbose_name': 'Ponencia',
                'verbose_name_plural': 'Ponencias',
                'ordering': ['-postulada_en'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(help_text='Nombre del campo tal como aparece en formulario_postulacion.', max_length=100)),
                ('valor', models.TextField(blank=True)),
                ('ponencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='submissions.ponencia')),
            ],
            options={
                'verbose_name': 'Respuesta de formulario',
                'verbose_name_plural': 'Respuestas de formulario',
                'unique_together': {('ponencia', 'nombre_campo')},
            },
        ),
    ]
