# Generated by Django 5.2 on 2026-05-14 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ponencia',
            constraint=models.UniqueConstraint(fields=('autor_principal', 'conferencia'), name='unique_autor_por_conferencia'),
        ),
    ]
