# Generated by Django 5.2 on 2026-06-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_unique_autor_por_conferencia'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ponencia',
            name='unique_autor_por_conferencia',
        ),
    ]
