# Generated by Django 5.2 on 2026-06-24 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_alter_conferenciausuario_rol'),
        ('submissions', '0003_remove_ponencia_unique_autor_por_conferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponencia',
            name='conferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponencias', to='conferences.conferencia'),
        ),
    ]
