# Generated by Django 5.2 on 2026-06-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_make_conferencia_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponencia',
            name='conferencia',
        ),
    ]
