# Generated by Django 5.2 on 2026-05-10 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionRevisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_desempate', models.BooleanField(default=False, help_text='RF-14: True si este revisor fue asignado para romper un empate.')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('ponencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='submissions.ponencia')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_revision', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de revisor',
                'verbose_name_plural': 'Asignaciones de revisores',
                'unique_together': {('ponencia', 'revisor')},
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas_rubrica', models.JSONField(default=dict, help_text='Respuestas a cada criterio de la rúbrica de la conferencia.')),
                ('comentario_privado', models.TextField(blank=True, help_text='Solo visible para el organizador. NUNCA se envía al autor.')),
                ('comentario_autor', models.TextField(blank=True, help_text='RF-18: feedback anónimo que sí recibe el autor.')),
                ('veredicto', models.CharField(blank=True, choices=[('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('aceptado_con_cambios', 'Aceptado con cambios')], max_length=25)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada')], default='pendiente', max_length=15)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('asignacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='reviews.asignacionrevisor')),
            ],
            options={
                'verbose_name': 'Revisión',
                'verbose_name_plural': 'Revisiones',
            },
        ),
        migrations.CreateModel(
            name='Veredicto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('aceptado_con_cambios', 'Aceptado con cambios')], max_length=25)),
                ('resumen_para_autor', models.TextField(blank=True, help_text='RF-18: síntesis anónima del feedback para el autor.')),
                ('plazo_cambios', models.DateField(blank=True, help_text='RF-16: fecha límite para que el autor envíe cambios.', null=True)),
                ('notificado', models.BooleanField(default=False)),
                ('emitido_en', models.DateTimeField(auto_now_add=True)),
                ('emitido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veredictos_emitidos', to=settings.AUTH_USER_MODEL)),
                ('ponencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veredicto', to='submissions.ponencia')),
            ],
            options={
                'verbose_name': 'Veredicto',
                'verbose_name_plural': 'Veredictos',
            },
        ),
    ]
